apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
    component: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
        component: backend
    spec:
      containers:
        - name: order-service
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80